version: '3'
services:
  postgres_aurora:
    image: postgres:latest
    ports:
      - '5432:5432'
    volumes:
      - /data/postgres:/data/postgres
    env_file:
      - .env.local
    networks:
      - postgres

networks:
  postgres:
    driver: bridge
